apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gvp
stringData:
  ACCESS_KEY_ID: GOOG1EZ4OF3XFKGI7CX2GZ5BFXIAAWWTRPFIS7HSPUSPVCUMAEGEARWQEF3LI
  SECRET_ACCESS_KEY: eSWazIQkobuuVYQfARlxrBk6y/YiPfT9eIOW9ogK
  BUCKET_HOST: storage.googleapis.com
  BUCKET_NAME: gca-gsp-storage-bucket-gts
  BUCKET_PORT: "443"
  KAFKA_ADDR: infra-kafka-cp-kafka.infra.svc.cluster.local