# no of instances to be created during starup default is 1
deployment:
  namespace: ${NS}
  replicaCount: 1

# override the registry from where the image will be deployed
image:
  registry: $IMAGE_REGISTRY
  pullPolicy: Always
  imagePullSecrets: "pullsecret"

# Set the redis port to be used. 
context:
  envs:
    redis:
      port: 6379

# Set the consul volume to be mounted
secrets:
  kafka:                                                       
    volumes:
      - name: kafka-shared-secret-westus2-dev
        secret:
          secretName: kafka-secrets-token
      - name: kafka-shared-secret-eastus2-dev
        secret:
          secretName: kafka-secrets-token
  consulACL:
    volumes:
    - name: consul-shared-secret
      secret:
        secretName: consul-voice-token

# Enable HPA and set the target CPU and memory for scale up and down
hpa:
  targetCPUPercent: 60
  targetMemoryPercent: 60
  enabled: true  

prometheus:
  # Enable for Prometheus Annotation
  metricServer:
    enabled: false
    path: /metrics

  # Enable for Prometheus operator
  podMonitor:
    enabled: false
    path: /metrics
    interval: 30s
    scrapeTimeout: