apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gws
stringData:
  gws_redis_password: redpass
  gws_consul_token: INSERT_CONSUL_TOKEN
  POSTGRES_ADDR: pgdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gws_pg_user: pgUser
  gws_pg_pass: pgPass
  gws_as_pg_user: asUser
  gws_as_pg_pass: asPass
  gws_app_provisioning: sample
  gws_app_workspace: sample
  gws_client_id: external_api_client
  gws_client_secret: R2VuZXN5czEyMzQ=
  gws_ops_user: opsUser
  gws_ops_pass_encr: opsPass
  DB_NAME_GWS: gws_db
  DB_NAME_PROV: prov_db
  ES_ADDR: elastic-es-http.infra
  REDIS_ADDR: infra-redis-redis-cluster.infra
  global_location: usw2