apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: uscx
stringData:
  POSTGRES_ADDR: pgdb-ucsx-postgresql.infra.svc.cluster.local
  DB_NAME_UCSX: ucsx
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  ucsx_gauth_client_id: ucsx_api_client
  ucsx_gauth_client_secret: secret
  ucsx_tenant_100_db_name: ucsx_t100
  ucsx_tenant_100_db_password: ucsx
  ucsx_tenant_100_db_user: ucsx_t100
  ucsx_sid: "100"
  ucsx_tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  ES_ADDR: opensearch-cluster-master.infra.svc.cluster.local