apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: iwd
stringData:
  POSTGRES_ADDR: pgdb-dgt-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  iwd_db_user: iwd-100
  iwd_db_password: iwd-100
  iwd_redis_password: INSERT_REDIS_PASSWORD
  iwd_gws_client_id: iwd_client
  iwd_gws_client_secret: secret
  tenant_sid: "100"
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  iwd_gws_api_key: iwd_client
  iwd_nexus_api_key: e8a87cf6-6153-4e7f-aa8f-71652de59f98
  iwd_tenant_api_key: 39f4b044-968e-44ba-87b4-7504f6da00f5
  iwd_tenant_api_key_iwddm: 20993434-e6fb-4081-9b1f-5c5a7e523077
  iwd_tenant_api_key_tenant: e0c519c2-a9d5-48cc-8da9-8566fcce6575
  ES_ADDR: elastic-es-http.infra.svc.cluster.local